---
kind: pipeline
name: secreter
steps:

- name: test
  image: l.gcr.io/google/bazel:0.28.1
  commands:
  - ./hack/build/test.sh
  volumes:
  - name: cache
    path: /root/.cache

- name: build and push docker image
  image: l.gcr.io/google/bazel:0.28.1
  environment:
    DOCKER_AUTH:
      from_secret: docker-config-json
  commands:
  - ./hack/build/push-image.sh
  volumes:
  - name: cache
    path: /root/.cache
  when:
    ref:
    - refs/heads/master
    - refs/tags/v*

- name: build binaries
  image: l.gcr.io/google/bazel:0.28.1
  commands:
  - ./hack/build/binaries.sh
  volumes:
  - name: cache
    path: /root/.cache
  when:
    ref:
    - refs/tags/v*

- name: release binaries
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-release-token
    files: bazel-bin/cmd/cli/*.tgz
    checksum:
    - sha512
  volumes:
  - name: cache
    path: /root/.cache
  when:
    ref:
    - refs/tags/v*

volumes:
- name: cache
  temp: {}
---
kind: signature
hmac: 7373b011bd1cc7a99f8084d82be05ac15a1546bf7d158af8e39eac7a01e29e61

...
