apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secretencryptionconfigs.k8s.amaiz.com
spec:
  group: k8s.amaiz.com
  names:
    kind: SecretEncryptionConfig
    listKind: SecretEncryptionConfigList
    plural: secretencryptionconfigs
    singular: secretencryptionconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
          type: object
        providers:
          description: Providers is the list of encryption providers to be used. The
            first one is the primary provider that will be used for encryption.
          items:
            minimum: 1
            properties:
              curve25519:
                description: Curve25519 defines the configuration of the local Curve25519
                  provider
                properties:
                  keyStore:
                    description: Reference to a secret containing a key store with
                      Curve25519 key pairs
                    type: object
                  rotationSchedule:
                    description: Key rotation schedule in Cron format, see https://en.wikipedia.org/wiki/Cron.
                    type: string
                required:
                - keyStore
                type: object
              gcpkms:
                description: GCPKMS defines the configuration of the GCP KMS provider
                properties:
                  credentials:
                    description: List of references to keys of Secrets containing
                      GCP credential files, see https://cloud.google.com/iam/docs/creating-managing-service-account-keys
                    items:
                      properties:
                        secretKeyRef:
                          description: Selects a key of a Secret in the same namespace
                          type: object
                      required:
                      - secretKeyRef
                      type: object
                    type: array
                  cryptoKeyID:
                    description: Key resource ID, see https://cloud.google.com/kms/docs/object-hierarchy#key
                    type: string
                  cryptoKeyVersion:
                    description: Key version resource ID (needed for asymmetric decryption),
                      see https://cloud.google.com/kms/docs/object-hierarchy#key_version
                    type: string
                  keyRingID:
                    description: Key ring resource ID, see https://cloud.google.com/kms/docs/object-hierarchy#key_ring
                    type: string
                  locationID:
                    description: KMS location ID, see https://cloud.google.com/kms/docs/object-hierarchy#location
                    type: string
                  projectID:
                    description: GCP project ID, see https://cloud.google.com/kms/docs/object-hierarchy#project
                    type: string
                required:
                - projectID
                - locationID
                - keyRingID
                - cryptoKeyID
                - credentials
                type: object
              name:
                description: Name is the name of the provider to be used.
                pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                type: string
            required:
            - name
            type: object
          minimum: 1
          type: array
        status:
          description: Status contains the information about public keys of the primary
            encryption provider (if applicable), observed state of the configuration,
            etc.
          properties:
            publicKey:
              description: PublicKey is the current primary PublicKey used for encryption
              type: string
          type: object
      required:
      - providers
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
