---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secreter
subjects:
- kind: ServiceAccount
  name: secreter
  namespace: secreter
roleRef:
  kind: ClusterRole
  name: secreter
  apiGroup: rbac.authorization.k8s.io
