---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secreter
  namespace: secreter
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - secreter
  resources:
  - deployments/finalizers
  verbs:
  - update
